name: Start release

on: 
  push:
    branches:
      - master
      - next

jobs:
  start-deploy:
    runs-on: ubuntu-latest
    name: Deploy npm package
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run test
      - run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}